on:
 workflow_dispatch:
 push:
   branches:
     - main

env:
  github_token: "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: build
      run: docker build . --secret id=github_token,env=github_token,target=/root/.npmrc
