on:
 workflow_dispatch:
 push:
   branches:
     - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: build
      run: docker build .
